hydra:
  searchpath:
    - file://verl/trainer/config

defaults:
  - ppo_trainer
  - _self_

data:
  gen_batch_size: ${data.train_batch_size}

actor_rollout_ref:
  actor:
    is_clip: true
    kalman_Q: 1e-6
    kalman_R: 1.0

trainer:
  project_name: verl-kpo
